#!/usr/bin/env bash
set -euo pipefail

# Step 4: Calculate loss for all datasets
# This script calculates loss on poisoned datasets generated by Step 3

# Load common environment
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/env.sh"

# Configuration from presets
POISONING_PERCENTAGES=("${all_POISONING_PERCENTAGES[@]}")
POISONING_PERCENTAGES_consecutive=("${all_POISONING_PERCENTAGES_consecutive[@]}")
real_dataset_names=("${all_real_dataset_names[@]}")
sync_dataset_names=("${all_sync_dataset_names[@]}")
ns=("${all_ns[@]}")
ns_consecutive=("${all_ns_consecutive[@]}")
seeds=("${all_seeds[@]}")
Rs=("${all_Rs[@]}")
Rs_consecutive=("${all_Rs_consecutive[@]}")
brute_force_POISONING_PERCENTAGES=("${all_brute_force_POISONING_PERCENTAGES[@]}")
brute_force_ns=("${all_brute_force_ns[@]}")
brute_force_Rs=("${all_brute_force_Rs[@]}")

# Parse command line arguments
ALL_MODE=false
ALL_ONE_SEED_MODE=false
QUICK_MODE=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --all)
            ALL_MODE=true
            shift
            ;;
        --all-one-seed)
            ALL_ONE_SEED_MODE=true
            seeds=("${one_seed_seeds[@]}")
            shift
            ;;
        --quick)
            QUICK_MODE=true
            POISONING_PERCENTAGES=("${quick_POISONING_PERCENTAGES[@]}")
            real_dataset_names=("${quick_real_dataset_names[@]}")
            sync_dataset_names=("${quick_sync_dataset_names[@]}")
            ns=("${quick_ns[@]}")
            seeds=("${quick_seeds[@]}")
            Rs=("${quick_Rs[@]}")
            brute_force_POISONING_PERCENTAGES=("${quick_brute_force_POISONING_PERCENTAGES[@]}")
            base_brute_force_POISONING_PERCENTAGE="${quick_brute_force_POISONING_PERCENTAGES[0]}"
            brute_force_ns=("${quick_brute_force_ns[@]}")
            brute_force_Rs=("${quick_brute_force_Rs[@]}")
            shift
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: $0 --all|--all-one-seed|--quick"
            exit 1
            ;;
    esac
done

# Ensure mode specified
if [ "$ALL_MODE" = false ] && [ "$ALL_ONE_SEED_MODE" = false ] && [ "$QUICK_MODE" = false ]; then
    echo "Error: Either --all, --all-one-seed, or --quick option must be specified"
    echo "Usage: $0 --all|--all-one-seed|--quick"
    exit 1
fi

echo "Step 4: Calculating loss for poisoned datasets..."
echo "  Data directory: $DATA_DIR"
echo "  Results directory: $RESULTS_DIR"
echo "  Base poisoning percentage: $base_POISONING_PERCENTAGE"
echo "  Base n: $base_n"
echo "  Base R: $base_R"
echo ""

# Prepare results directory
mkdir -p "$RESULTS_DIR/loss"
mkdir -p "$RESULTS_DIR/loss_consecutive"
mkdir -p "$RESULTS_DIR/loss_consecutive_w_endpoints"
mkdir -p "$RESULTS_DIR/loss_duplicate_allowed"
mkdir -p "$RESULTS_DIR/loss_consecutive_w_endpoints_using_relaxed_solution"
mkdir -p "$RESULTS_DIR/loss_random"

# Move to build directory to run binaries
cd "$BUILD_DIR"

# Function to calculate loss for a dataset
run_calc_loss_variant() {
    local variant_dir="$1"
    local log_suffix="$2"
    local input_file_name="$3"
    local legitimate_file_name="$4"
    local poison_num="$5"
    local base_output_name="$6"
    local dataset_name="$7"
    local n_value="$8"

    if [ ! -f "$DATA_DIR/${input_file_name}" ]; then
        echo "    Input file not found: $DATA_DIR/${input_file_name}"
        return
    fi

    if [ ! -f "$DATA_DIR/${legitimate_file_name}" ]; then
        echo "    Legitimate file not found: $DATA_DIR/${legitimate_file_name}"
        return
    fi

    local out_dir="$RESULTS_DIR/${variant_dir}/${dataset_name}/n${n_value}/lambda${poison_num}"
    local loss_json_file="$out_dir/${base_output_name}_loss.json"
    mkdir -p "$out_dir"

    if [ -f "$loss_json_file" ]; then
        echo "    [Skipped] Output JSON already exists: ${base_output_name}_loss.json"
        return
    fi

    echo "    Calculating loss for: $input_file_name (lambda=$poison_num${log_suffix})"
    if ./calc_loss "$DATA_DIR/${input_file_name}" "$DATA_DIR/${legitimate_file_name}" "$loss_json_file" 2>/dev/null; then
        echo "      Loss calculation completed"
    else
        echo "      [ERROR] Error calculating loss for $input_file_name"
        exit 1
    fi
}

run_calc_loss() {
    run_calc_loss_variant "loss" "" "$@"
}

run_calc_loss_consecutive() {
    run_calc_loss_variant "loss_consecutive" ", consecutive" "$@"
}

run_calc_loss_consecutive_w_endpoints() {
    run_calc_loss_variant "loss_consecutive_w_endpoints" ", consecutive with endpoints" "$@"
}

run_calc_loss_consecutive_w_endpoints_duplicate_allowed() {
    run_calc_loss_variant "loss_consecutive_w_endpoints_duplicate_allowed" ", consecutive with endpoints duplicate allowed" "$@"
}

run_calc_loss_consecutive_w_endpoints_using_relaxed_solution() {
    run_calc_loss_variant "loss_consecutive_w_endpoints_using_relaxed_solution" ", consecutive with endpoints using relaxed solution" "$@"
}

run_calc_loss_duplicate_allowed() {
    run_calc_loss_variant "loss_duplicate_allowed" ", duplicate allowed" "$@"
}

run_calc_loss_random() {
    run_calc_loss_variant "loss_random" ", random" "$@"
}


# Function to process real datasets with given parameters
process_real_datasets_generic() {
    local loss_func="$1"
    local n_val="$2"
    local percentage="$3"
    local input_suffix="$4"
    local output_suffix="$5"
    local include_legit="$6"

    local poison_num=$((n_val * percentage / 100))

    for real_dataset_name in "${real_dataset_names[@]}"; do
        for seed in "${seeds[@]}"; do
            for dtype in "uint64"; do
                # Legitimate dataset (only for baseline parameters)
                if [ "$include_legit" = "true" ] && \
                   [ "$n_val" = "$base_n" ] && \
                   [ "$percentage" = "$base_POISONING_PERCENTAGE" ]; then
                    local input_legit="${real_dataset_name}_n${n_val}_seed${seed}_${dtype}"
                    local base_out_legit="${real_dataset_name}_n${n_val}_seed${seed}_${dtype}"
                    echo "Processing: $real_dataset_name n=$n_val seed=$seed dtype=$dtype (legitimate)"
                    # For legitimate case, input and legitimate file are the same
                    run_calc_loss "$input_legit" "$input_legit" "0" "$base_out_legit" "$real_dataset_name" "$n_val"
                fi

                # Poisoned dataset
                echo "Processing: $real_dataset_name n=$n_val seed=$seed dtype=$dtype percentage=$percentage${output_suffix:+ ($output_suffix)}"
                local base_prefix="${real_dataset_name}_n${n_val}_seed${seed}"
                local input_file_name="${base_prefix}_lambda${poison_num}${input_suffix}_${dtype}"
                local base_output_name="${base_prefix}_lambda${poison_num}${output_suffix}_percentage${percentage}_${dtype}"
                local legitimate_file_name="${base_prefix}_${dtype}"

                "$loss_func" "$input_file_name" "$legitimate_file_name" "$poison_num" "$base_output_name" "$real_dataset_name" "$n_val"
            done
        done
    done
}

# Function to process synthetic datasets with given parameters
process_sync_datasets_generic() {
    local loss_func="$1"
    local n_val="$2"
    local R_val="$3"
    local percentage="$4"
    local input_suffix="$5"
    local output_suffix="$6"
    local include_legit="$7"

    local poison_num=$((n_val * percentage / 100))

    for sync_dataset_name in "${sync_dataset_names[@]}"; do
        for seed in "${seeds[@]}"; do
            for dtype in "uint64"; do
                # Legitimate dataset (only for baseline parameters)
                if [ "$include_legit" = "true" ] && \
                   [ "$n_val" = "$base_n" ] && \
                   [ "$R_val" = "$base_R" ] && \
                   [ "$percentage" = "$base_POISONING_PERCENTAGE" ]; then
                    local input_legit="${sync_dataset_name}_n${n_val}_R${R_val}_seed${seed}_${dtype}"
                    local base_out_legit="${sync_dataset_name}_n${n_val}_R${R_val}_seed${seed}_${dtype}"
                    echo "Processing: $sync_dataset_name n=$n_val R=$R_val seed=$seed dtype=$dtype (legitimate)"
                    # For legitimate case, input and legitimate file are the same
                    run_calc_loss "$input_legit" "$input_legit" "0" "$base_out_legit" "$sync_dataset_name" "$n_val"
                fi

                # Poisoned dataset
                echo "Processing: $sync_dataset_name n=$n_val R=$R_val seed=$seed dtype=$dtype percentage=$percentage${output_suffix:+ ($output_suffix)}"
                local base_prefix="${sync_dataset_name}_n${n_val}_R${R_val}_seed${seed}"
                local input_file_name="${base_prefix}_lambda${poison_num}${input_suffix}_${dtype}"
                local base_output_name="${base_prefix}_lambda${poison_num}${output_suffix}_percentage${percentage}_${dtype}"
                local legitimate_file_name="${base_prefix}_${dtype}"

                "$loss_func" "$input_file_name" "$legitimate_file_name" "$poison_num" "$base_output_name" "$sync_dataset_name" "$n_val"
            done
        done
    done
}



# ======================================================================
# Thin wrappers for real datasets
# ======================================================================

# Baseline (no suffix, includes legitimate)
process_real_datasets_loss() {
    local n_val="$1"
    local percentage="$2"
    process_real_datasets_generic \
        "run_calc_loss" \
        "$n_val" \
        "$percentage" \
        "" \
        "" \
        "true"
}

# Consecutive
process_real_datasets_consecutive_loss() {
    local n_val="$1"
    local percentage="$2"
    process_real_datasets_generic \
        "run_calc_loss_consecutive" \
        "$n_val" \
        "$percentage" \
        "_consecutive" \
        "_consecutive" \
        "false"
}

# Consecutive with endpoints
process_real_datasets_consecutive_w_endpoints_loss() {
    local n_val="$1"
    local percentage="$2"
    process_real_datasets_generic \
        "run_calc_loss_consecutive_w_endpoints" \
        "$n_val" \
        "$percentage" \
        "_consecutive_w_endpoints" \
        "_consecutive_w_endpoints" \
        "false"
}

# Duplicate allowed
process_real_datasets_duplicate_allowed_loss() {
    local n_val="$1"
    local percentage="$2"
    process_real_datasets_generic \
        "run_calc_loss_duplicate_allowed" \
        "$n_val" \
        "$percentage" \
        "_duplicate_allowed" \
        "_duplicate_allowed" \
        "false"
}

# Random
process_real_datasets_random_loss() {
    local n_val="$1"
    local percentage="$2"
    process_real_datasets_generic \
        "run_calc_loss_random" \
        "$n_val" \
        "$percentage" \
        "_random" \
        "_random" \
        "false"
}

# Consecutive with endpoints (duplicate allowed)
process_real_datasets_consecutive_w_endpoints_duplicate_allowed_loss() {
    local n_val="$1"
    local percentage="$2"
    process_real_datasets_generic \
        "run_calc_loss_consecutive_w_endpoints_duplicate_allowed" \
        "$n_val" \
        "$percentage" \
        "_consecutive_w_endpoints_duplicate_allowed" \
        "_consecutive_w_endpoints_duplicate_allowed" \
        "false"
}

# Consecutive with endpoints (using relaxed solution)
process_real_datasets_consecutive_w_endpoints_using_relaxed_solution_loss() {
    local n_val="$1"
    local percentage="$2"
    process_real_datasets_generic \
        "run_calc_loss_consecutive_w_endpoints_using_relaxed_solution" \
        "$n_val" \
        "$percentage" \
        "_consecutive_w_endpoints_using_relaxed_solution" \
        "_consecutive_w_endpoints_using_relaxed_solution" \
        "false"
}


# ======================================================================
# Thin wrappers for synthetic datasets
# ======================================================================

# Baseline (no suffix, includes legitimate)
process_sync_datasets_loss() {
    local n_val="$1"
    local R_val="$2"
    local percentage="$3"
    process_sync_datasets_generic \
        "run_calc_loss" \
        "$n_val" \
        "$R_val" \
        "$percentage" \
        "" \
        "" \
        "true"
}

# Consecutive
process_sync_datasets_consecutive_loss() {
    local n_val="$1"
    local R_val="$2"
    local percentage="$3"
    process_sync_datasets_generic \
        "run_calc_loss_consecutive" \
        "$n_val" \
        "$R_val" \
        "$percentage" \
        "_consecutive" \
        "_consecutive" \
        "false"
}

# Consecutive with endpoints
process_sync_datasets_consecutive_w_endpoints_loss() {
    local n_val="$1"
    local R_val="$2"
    local percentage="$3"
    process_sync_datasets_generic \
        "run_calc_loss_consecutive_w_endpoints" \
        "$n_val" \
        "$R_val" \
        "$percentage" \
        "_consecutive_w_endpoints" \
        "_consecutive_w_endpoints" \
        "false"
}

# Duplicate allowed
process_sync_datasets_duplicate_allowed_loss() {
    local n_val="$1"
    local R_val="$2"
    local percentage="$3"
    process_sync_datasets_generic \
        "run_calc_loss_duplicate_allowed" \
        "$n_val" \
        "$R_val" \
        "$percentage" \
        "_duplicate_allowed" \
        "_duplicate_allowed" \
        "false"
}

# Random
process_sync_datasets_random_loss() {
    local n_val="$1"
    local R_val="$2"
    local percentage="$3"
    process_sync_datasets_generic \
        "run_calc_loss_random" \
        "$n_val" \
        "$R_val" \
        "$percentage" \
        "_random" \
        "_random" \
        "false"
}

# Consecutive with endpoints (duplicate allowed)
process_sync_datasets_consecutive_w_endpoints_duplicate_allowed_loss() {
    local n_val="$1"
    local R_val="$2"
    local percentage="$3"
    process_sync_datasets_generic \
        "run_calc_loss_consecutive_w_endpoints_duplicate_allowed" \
        "$n_val" \
        "$R_val" \
        "$percentage" \
        "_consecutive_w_endpoints_duplicate_allowed" \
        "_consecutive_w_endpoints_duplicate_allowed" \
        "false"
}

# Consecutive with endpoints (using relaxed solution)
process_sync_datasets_consecutive_w_endpoints_using_relaxed_solution_loss() {
    local n_val="$1"
    local R_val="$2"
    local percentage="$3"
    process_sync_datasets_generic \
        "run_calc_loss_consecutive_w_endpoints_using_relaxed_solution" \
        "$n_val" \
        "$R_val" \
        "$percentage" \
        "_consecutive_w_endpoints_using_relaxed_solution" \
        "_consecutive_w_endpoints_using_relaxed_solution" \
        "false"
}


# ======================================================================
# Main experiments
# ======================================================================

# Experiment 1: Vary n while keeping base_R and base_POISONING_PERCENTAGE
echo "  Experiment 1: Varying n (base_R=$base_R, base_POISONING_PERCENTAGE=$base_POISONING_PERCENTAGE)"
for n in "${ns[@]}"; do
    echo "    Varying n: $n"
    process_real_datasets_loss "$n" "$base_POISONING_PERCENTAGE"
    process_sync_datasets_loss "$n" "$base_R" "$base_POISONING_PERCENTAGE"
    process_real_datasets_duplicate_allowed_loss "$n" "$base_POISONING_PERCENTAGE"
    process_sync_datasets_duplicate_allowed_loss "$n" "$base_R" "$base_POISONING_PERCENTAGE"
    process_real_datasets_consecutive_w_endpoints_duplicate_allowed_loss "$n" "$base_POISONING_PERCENTAGE"
    process_sync_datasets_consecutive_w_endpoints_duplicate_allowed_loss "$n" "$base_R" "$base_POISONING_PERCENTAGE"
    process_real_datasets_consecutive_w_endpoints_using_relaxed_solution_loss "$n" "$base_POISONING_PERCENTAGE"
    process_sync_datasets_consecutive_w_endpoints_using_relaxed_solution_loss "$n" "$base_R" "$base_POISONING_PERCENTAGE"
    process_real_datasets_random_loss "$n" "$base_POISONING_PERCENTAGE"
    process_sync_datasets_random_loss "$n" "$base_R" "$base_POISONING_PERCENTAGE"
done

for n in "${ns_consecutive[@]}"; do
    echo "    Varying n (for consecutive): $n"
    process_real_datasets_consecutive_loss "$n" "$base_POISONING_PERCENTAGE"
    process_sync_datasets_consecutive_loss "$n" "$base_R" "$base_POISONING_PERCENTAGE"
    process_real_datasets_consecutive_w_endpoints_loss "$n" "$base_POISONING_PERCENTAGE"
    process_sync_datasets_consecutive_w_endpoints_loss "$n" "$base_R" "$base_POISONING_PERCENTAGE"
done

for n in "${brute_force_ns[@]}"; do
    echo "    Varying n (for brute force): $n"
    process_real_datasets_loss "$n" "$base_brute_force_POISONING_PERCENTAGE"
    process_sync_datasets_loss "$n" "$base_brute_force_R" "$base_brute_force_POISONING_PERCENTAGE"
    process_real_datasets_duplicate_allowed_loss "$n" "$base_brute_force_POISONING_PERCENTAGE"
    process_sync_datasets_duplicate_allowed_loss "$n" "$base_brute_force_R" "$base_brute_force_POISONING_PERCENTAGE"
    process_real_datasets_consecutive_w_endpoints_duplicate_allowed_loss "$n" "$base_brute_force_POISONING_PERCENTAGE"
    process_sync_datasets_consecutive_w_endpoints_duplicate_allowed_loss "$n" "$base_brute_force_R" "$base_brute_force_POISONING_PERCENTAGE"
    process_real_datasets_consecutive_w_endpoints_using_relaxed_solution_loss "$n" "$base_brute_force_POISONING_PERCENTAGE"
    process_sync_datasets_consecutive_w_endpoints_using_relaxed_solution_loss "$n" "$base_brute_force_R" "$base_brute_force_POISONING_PERCENTAGE"
    process_real_datasets_random_loss "$n" "$base_brute_force_POISONING_PERCENTAGE"
    process_sync_datasets_random_loss "$n" "$base_brute_force_R" "$base_brute_force_POISONING_PERCENTAGE"
done


# Experiment 2: Vary R while keeping base_n and base_POISONING_PERCENTAGE
echo "  Experiment 2: Varying R (base_n=$base_n, base_POISONING_PERCENTAGE=$base_POISONING_PERCENTAGE)"
for R in "${Rs[@]}"; do
    if [ "$R" -le "$base_n" ]; then
        continue
    fi
    echo "    Varying R: $R"
    process_sync_datasets_loss "$base_n" "$R" "$base_POISONING_PERCENTAGE"
    process_sync_datasets_duplicate_allowed_loss "$base_n" "$R" "$base_POISONING_PERCENTAGE"
    process_sync_datasets_consecutive_w_endpoints_duplicate_allowed_loss "$base_n" "$R" "$base_POISONING_PERCENTAGE"
    process_sync_datasets_consecutive_w_endpoints_using_relaxed_solution_loss "$base_n" "$R" "$base_POISONING_PERCENTAGE"
    process_sync_datasets_random_loss "$base_n" "$R" "$base_POISONING_PERCENTAGE"
done

for R in "${Rs_consecutive[@]}"; do
    echo "    Varying R (for consecutive): $R"
    process_sync_datasets_consecutive_loss "$base_n" "$R" "$base_POISONING_PERCENTAGE"
    # Temporarily disabled: Seg+E Vary R unused by current plots
    # process_sync_datasets_consecutive_w_endpoints_loss "$base_n" "$R" "$base_POISONING_PERCENTAGE"
done

for R in "${brute_force_Rs[@]}"; do
    if [ "$R" -le "$base_brute_force_n" ]; then
        continue
    fi
    echo "    Varying R (for brute force): $R"
    process_sync_datasets_loss "$base_brute_force_n" "$R" "$base_brute_force_POISONING_PERCENTAGE"
    process_sync_datasets_duplicate_allowed_loss "$base_brute_force_n" "$R" "$base_brute_force_POISONING_PERCENTAGE"
    process_sync_datasets_random_loss "$base_brute_force_n" "$R" "$base_brute_force_POISONING_PERCENTAGE"
done

for R in "${Rs_consecutive[@]}"; do
    echo "    Varying R (for consecutive): $R"
    process_sync_datasets_consecutive_loss "$base_brute_force_n" "$R" "$base_brute_force_POISONING_PERCENTAGE"
    # Temporarily disabled: Seg+E Vary R unused by current plots
    # process_sync_datasets_consecutive_w_endpoints_loss "$base_brute_force_n" "$R" "$base_brute_force_POISONING_PERCENTAGE"
    process_sync_datasets_consecutive_w_endpoints_duplicate_allowed_loss "$base_brute_force_n" "$R" "$base_brute_force_POISONING_PERCENTAGE"
    process_sync_datasets_consecutive_w_endpoints_using_relaxed_solution_loss "$base_brute_force_n" "$R" "$base_brute_force_POISONING_PERCENTAGE"
done


# Experiment 3: Varying poisoning percentage while keeping base_n and base_R
echo "  Experiment 3: Varying poisoning percentage (base_n=$base_n, base_R=$base_R)"
for percentage in "${POISONING_PERCENTAGES[@]}"; do
    echo "    Varying poisoning percentage: $percentage"
    process_real_datasets_loss "$base_n" "$percentage"
    process_sync_datasets_loss "$base_n" "$base_R" "$percentage"
    process_real_datasets_duplicate_allowed_loss "$base_n" "$percentage"
    process_sync_datasets_duplicate_allowed_loss "$base_n" "$base_R" "$percentage"
    process_real_datasets_consecutive_w_endpoints_duplicate_allowed_loss "$base_n" "$percentage"
    process_sync_datasets_consecutive_w_endpoints_duplicate_allowed_loss "$base_n" "$base_R" "$percentage"
    process_real_datasets_consecutive_w_endpoints_using_relaxed_solution_loss "$base_n" "$percentage"
    process_sync_datasets_consecutive_w_endpoints_using_relaxed_solution_loss "$base_n" "$base_R" "$percentage"
    process_real_datasets_random_loss "$base_n" "$percentage"
    process_sync_datasets_random_loss "$base_n" "$base_R" "$percentage"
done

for percentage in "${POISONING_PERCENTAGES_consecutive[@]}"; do
    echo "    Varying poisoning percentage (for consecutive): $percentage"
    process_real_datasets_consecutive_loss "$base_n" "$percentage"
    process_sync_datasets_consecutive_loss "$base_n" "$base_R" "$percentage"
    process_real_datasets_consecutive_w_endpoints_loss "$base_n" "$percentage"
    process_sync_datasets_consecutive_w_endpoints_loss "$base_n" "$base_R" "$percentage"
done

for percentage in "${brute_force_POISONING_PERCENTAGES[@]}"; do
    echo "    Varying poisoning percentage (for brute force): $percentage"
    process_real_datasets_loss "$base_brute_force_n" "$percentage"
    process_sync_datasets_loss "$base_brute_force_n" "$base_brute_force_R" "$percentage"
    process_real_datasets_duplicate_allowed_loss "$base_brute_force_n" "$percentage"
    process_sync_datasets_duplicate_allowed_loss "$base_brute_force_n" "$base_brute_force_R" "$percentage"
    process_real_datasets_consecutive_w_endpoints_duplicate_allowed_loss "$base_brute_force_n" "$percentage"
    process_sync_datasets_consecutive_w_endpoints_duplicate_allowed_loss "$base_brute_force_n" "$base_brute_force_R" "$percentage"
    process_real_datasets_consecutive_w_endpoints_using_relaxed_solution_loss "$base_brute_force_n" "$percentage"
    process_sync_datasets_consecutive_w_endpoints_using_relaxed_solution_loss "$base_brute_force_n" "$base_brute_force_R" "$percentage"
    process_real_datasets_random_loss "$base_brute_force_n" "$percentage"
    process_sync_datasets_random_loss "$base_brute_force_n" "$base_brute_force_R" "$percentage"
done

for percentage in "${POISONING_PERCENTAGES_consecutive[@]}"; do
    echo "    Varying poisoning percentage (for consecutive): $percentage"
    process_real_datasets_consecutive_loss "$base_brute_force_n" "$percentage"
    process_sync_datasets_consecutive_loss "$base_brute_force_n" "$base_brute_force_R" "$percentage"
    process_real_datasets_consecutive_w_endpoints_loss "$base_brute_force_n" "$percentage"
    process_sync_datasets_consecutive_w_endpoints_loss "$base_brute_force_n" "$base_brute_force_R" "$percentage"
done

echo "Loss calculation completed"
echo "  Results saved to: $RESULTS_DIR/loss/"
echo "  Consecutive results saved to: $RESULTS_DIR/loss_consecutive/"
echo "  Consecutive with endpoints results saved to: $RESULTS_DIR/loss_consecutive_w_endpoints/"
echo "  Consecutive with endpoints duplicate allowed results saved to: $RESULTS_DIR/loss_consecutive_w_endpoints_duplicate_allowed/"
echo "  Duplicate allowed results saved to: $RESULTS_DIR/loss_duplicate_allowed/"
echo ""

# Count JSON files for all approaches
total_loss_files=$(find "$RESULTS_DIR/loss/" -name "*.json" -type f | wc -l)
total_consecutive_files=$(find "$RESULTS_DIR/loss_consecutive/" -name "*.json" -type f | wc -l)
total_consecutive_w_endpoints_files=$(find "$RESULTS_DIR/loss_consecutive_w_endpoints/" -name "*.json" -type f | wc -l)
total_consecutive_w_endpoints_duplicate_allowed_files=$(find "$RESULTS_DIR/loss_consecutive_w_endpoints_duplicate_allowed/" -name "*.json" -type f | wc -l)
total_duplicate_allowed_files=$(find "$RESULTS_DIR/loss_duplicate_allowed/" -name "*.json" -type f | wc -l)
total_consecutive_w_endpoints_using_relaxed_solution_files=$(find "$RESULTS_DIR/loss_consecutive_w_endpoints_using_relaxed_solution/" -name "*.json" -type f | wc -l)
echo "    Total loss result files: $total_loss_files"
echo "    Total consecutive loss result files: $total_consecutive_files"
echo "    Total consecutive with endpoints loss result files: $total_consecutive_w_endpoints_files"
echo "    Total consecutive with endpoints duplicate allowed loss result files: $total_consecutive_w_endpoints_duplicate_allowed_files"
echo "    Total duplicate allowed loss result files: $total_duplicate_allowed_files"
echo "    Total consecutive with endpoints using relaxed solution result files: $total_consecutive_w_endpoints_using_relaxed_solution_files"
echo ""